<?php

namespace KikiceBundle\Repository;

/**
 * questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findQuestionInExpert($categorie)
    {
        $query = $this->createQueryBuilder('q')
            ->where('q.categorie=:categ')
            ->setParameter('categ', $categorie)
            ->getQuery();

        return $query->getResult();
    }
}
